@startuml diagram-c2-container

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!define SPRITESURL https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/v1.0/sprites

!include DEVICONS/react.puml
!include DEVICONS/nodejs.puml
!include DEVICONS/mongodb.puml

!include FONTAWESOME/users.puml
!include FONTAWESOME/python.puml
!include FONTAWESOME/php.puml
!include SPRITESURL/kong.puml
!include SPRITESURL/aws.puml

LAYOUT_WITH_LEGEND()

Person(payer, "Payer", "Pagador do pagamento",)

Person(receiver, "Receiver", "Recebedor de pagamentos")

System_Boundary(woovi, "Sismtea woovi") {
    Container(pix_credito_payment_link, "Link", "react", "Link de pagamento pix crédito", $sprite="react")

    Container(pix_credito_payment_admin, "Admin", "react", "Interface de administração de links de pagamentos", $sprite="react")

    ' Container(api_gateway, "Gateway Api", "kong", "Gateway de apis", $sprite="kong")

    Container(pix_credito_webhook, "Api Pix Webhook", "aws, kong, sqs, lambda", "Webhook para notificações de pagamento via pix crédito utilizando api gateway kong, sqs e lambda", $sprite="aws")

    Container(pix_credito_api, "Api Pix Credit", "nodejs", "Api pix crédito", $sprite="nodejs")

    ContainerDb(pix_credito_database, "Banco de dados Pix Credit", "mongodb", "Banco de dados pix crédito", $sprite="mongodb")
}

System_Boundary(cel_coin, "Sistema Cel Coin") {
    Container_Ext(cel_coin_api, "Cel Coin Api", "web", "Api da cel coin para pagamentos", $sprite="web")
}

Rel(payer, pix_credito_payment_link, "Faz pagamentos via", "https")

Rel(receiver, pix_credito_payment_admin, "Gera link de pagamento via", "https")

Rel(pix_credito_api, cel_coin_api, "Processa os pagamentos via", "https")

Rel(pix_credito_api, pix_credito_database, "Armazena e obtem os estados via", "mongodb")

Rel(pix_credito_payment_link, pix_credito_api, "Realiza o pagamento via api gateway kong pelo protocolo", "https")

Rel(pix_credito_payment_admin, pix_credito_api, "Gera link de pagamento via api gateway kong pelo protocolo", "https")

Rel(cel_coin_api, pix_credito_webhook, "Notifica pagamentos via api gateway kong pelo protocolo", "https")

Rel(pix_credito_webhook, pix_credito_api, "Redireciona as mensagens para o contexto pix crédito via api gateway kong pelo protocolo", "https")

@enduml