@startuml diagram-c1-context

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5

!include DEVICONS/react.puml
!include DEVICONS/nodejs.puml
!include DEVICONS/mysql.puml
!include FONTAWESOME/users.puml

LAYOUT_WITH_LEGEND()

Person(payer, "Payer", "Pagador do pagamento",)
Person(receiver, "Receiver", "Recebedor de pagamentos")

System(woovi, "Woovi", "Sistema woovi")

System_Ext(cel_coin, "Cel Coin", "Parceiro para pagamentos via pix e cartão de crédito")

Rel(payer, woovi, "Faz pagamentos via", "https")

Rel(receiver, woovi, "Gera link de pagamento via", "https")

Rel(woovi, cel_coin, "Processa os pagamentos via", "https")

Rel(cel_coin, woovi, "Notifica pagamentos via", "https") 

@enduml